### PR TITLE
Fix on Annotation order and custom annotations

### LINKED ISSUE #289: WrongAnnotationError problem with Custom annotations
When custom annotations are present, `WrongAnnotationError` expects custom ones to be at the end. It can be seen here that it expects Inject to be before any custom annotation: https://github.com/vanniktech/lint-rules/blob/master/lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/AnnotationOrderDetectorTest.kt#L349

This particular instance works well. But it is a problem when used with Kotlin. Kotlin puts Nullable, NonNull annotations automatically. That means when used together with custom annotation, it will always result in an error. 

The following instance for example: 
```
@BindingAdapter("toolbarSubtitle")
fun Toolbar.setToolbarSubtitle(text: String?) {
    text?.let {
        subtitle = text
    }
}
```

There is no way to fix the given warning since there is only a single annotation.

I was gonna open a PR by just ignoring custom annotations. It is a small change in the code and fixes the issue. But then the given test above was breaking.

What do you think? Should I do that?

### PR DESCRIPTION
**Pull request by tasomaniac**
More details on the issue #289 

Kept backward compatibility. All custom annotations are enforced to be at the end. 

Fixed the Kotlin problem by ignoring fully quantified names of Jetbrains nullity annotations.

_Note:_ With this approach the lintFix issue described in #283 is also going to be fixed.

Fixes #289 #283

### CODE REVIEW

File: lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/AnnotationOrderDetectorTest.kt [hunk 1]
```diff
@@ -226,6 +226,30 @@ class AnnotationOrderDetectorTest {
...
+        .expect("""
+            |src/foo/MyTest.java:4: Warning: Annotations are in wrong order. Should be @Singleton @NonNull @Custom [WrongAnnotationOrder]
+            |  @Custom @NonNull @Singleton void test() { }
+            |                                   ~~~~
+            |0 errors, 1 warnings""".trimMargin())
+        .expectFixDiffs("""
+            |Fix for src/foo/MyTest.java line 4: Fix order:
+            |@@ -4 +4
+            |-   @Custom @NonNull @Singleton void test() { }
+            |+   @Singleton @NonNull @Custom void test() { }
```
Comment (tasomaniac) [inline lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/AnnotationOrderDetectorTest.kt]: As can be seen here, custom annotations are still kept with the `lintFix` task.

File: lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/AnnotationOrderDetectorTest.kt [hunk 2]
```diff
@@ -346,24 +370,6 @@ class AnnotationOrderDetectorTest {
         .expectClean()
   }
 
-  @Test fun injectBeforeCustom() {
```
Comment (vanniktech) [inline lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/AnnotationOrderDetectorTest.kt]: We should try to keep this behavior. It's super helpful.

File: lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/AnnotationOrderDetectorTest.kt [hunk 3]
```diff
@@ -613,4 +637,18 @@ class AnnotationOrderDetectorTest {
...
   }
+
+  @Test fun customNullableAnnotation() {
+    lint()
+        .allowCompilationErrors()
+        .files(java("""
+            package foo;
+
+            public class MyTest {
+              @Custom @Nullable public void myTest() { }
```
Comment (vanniktech) [inline lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/AnnotationOrderDetectorTest.kt]: Should not it be `@Nullable @Custom` here? Also to be consistent with singletonBeforeNonNullBeforeCustom

Comment (tasomaniac) [reply lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/AnnotationOrderDetectorTest.kt]: In the SingletonBeforeNonNull case the problem that the Singleton is before nonnull. I was checking the fix there. 

Here this is correct. In the original logic, custom annotations are always forced to be the end. This was not valid before. Now they should be clean.

File: lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/AnnotationOrderDetector.kt [hunk 4]
```diff
@@ -166,34 +172,19 @@ class AnnotationOrderDetector : Detector(), UastScanner {
...
-
-            return@all true
-          }
-
-      if (!isInCorrectOrder && numberOfRecognizedAnnotations > 0) {
+      if (!isInCorrectOrder && recognizedAnnotations.isNotEmpty()) {
         val correctOrder = annotationOrder
-            .filter { annotations.contains(it) }
-            .plus(annotations.filterNot { annotationOrder.contains(it) })
+            .filter { recognizedAnnotations.contains(it) }
```
Comment (tasomaniac) [inline lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/AnnotationOrderDetector.kt]: Kept this part. Thanks to `partition` above we have this part more readable.

File: lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/AnnotationOrderDetector.kt [hunk 5]
```diff
@@ -208,5 +199,24 @@ class AnnotationOrderDetector : Detector(), UastScanner {
         context.report(ISSUE_WRONG_ANNOTATION_ORDER, element, context.getNameLocation(element), "Annotations are in wrong order. Should be $correctOrder", fix)
       }
     }
+
+    private fun isInCorrectOrder(annotations: List<String>): Boolean {
```
Comment (tasomaniac) [inline lint-rules-android-lint/src/main/java/com/vanniktech/lintrules/android/AnnotationOrderDetector.kt]: Extracted but no change is done.

File: lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/AnnotationOrderDetectorTest.kt [hunk 6]
```diff
@@ -226,6 +226,30 @@ class AnnotationOrderDetectorTest {
             |+   @Binds @Singleton @NonNull void test() { }
             |""".trimMargin())
   }
+  
+  @Test fun singletonBeforeNonNullBeforeCustom() {
```
Comment (tasomaniac) [inline lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/AnnotationOrderDetectorTest.kt]: Kept this one. Not strictly about the issue but verifies that the `lintFix` puts the custom annotation to the end.

File: lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/AnnotationOrderDetectorTest.kt [hunk 7]
```diff
@@ -613,4 +637,22 @@ class AnnotationOrderDetectorTest {
...
         .expectClean()
   }
+
+  @Test fun kotlinCustomAnnotationOnNullableReturn() {
+    lint()
+        .allowCompilationErrors()
+        .files(kt("""
+            package foo
+
+            annotation class Custom
```
Comment (tasomaniac) [inline lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/AnnotationOrderDetectorTest.kt]: Initially I had this in Kotlin but didn't manage to make it fail. It was because of this line missing. In Java sources adding just `Custom` is valid. But in Kotlin, it is just ignored even when `allowCompilationErrors` is set.
